import * as esbuild from 'esbuild'
import { build as viteBuild } from 'vite'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'
import { mkdirSync, existsSync, cpSync, readFileSync, writeFileSync, rmSync, statSync } from 'fs'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const isWatch = process.argv.includes('--watch')

// Ensure dist directory exists
mkdirSync(resolve(__dirname, 'dist'), { recursive: true })

/**
 * Package binary U²-NetP ONNX model (4.57 MB) into safe chunks for singlefile bundling
 */
function packageU2NetPModel() {
  const modelPath = resolve(__dirname, 'assets/models/u2netp/u2netp.onnx')
  if (!existsSync(modelPath)) {
    throw new Error(`U2NetP ONNX model not found at ${modelPath}`)
  }

  let stats = statSync(modelPath)
  let sizeMB = stats.size / (1024 * 1024)
  if (sizeMB < 4.0 || sizeMB > 5.2) {
    const downloadPath = 'C:/Users/brijesh9177/Downloads/u2netp.onnx'
    if (existsSync(downloadPath)) {
      cpSync(downloadPath, modelPath)
      stats = statSync(modelPath)
      sizeMB = stats.size / (1024 * 1024)
      console.log('🔄 Auto-restored pristine u2netp.onnx from Downloads')
    }
  }

  if (sizeMB < 4.0 || sizeMB > 5.2) {
    throw new Error(`Unexpected U2NetP model file size: ${stats.size} bytes (${sizeMB.toFixed(2)} MB). Expected ~4.57 MB.`)
  }

  const buf = readFileSync(modelPath)
  const CHUNK_SIZE = 192 * 1024 // 192 KB binary -> ~256 KB base64 chunk
  const chunks = []
  for (let i = 0; i < buf.length; i += CHUNK_SIZE) {
    chunks.push(buf.subarray(i, i + CHUNK_SIZE).toString('base64'))
  }

  const chunksTsPath = resolve(__dirname, 'src/ai/u2netp_chunks.ts')
  const content = `// Auto-generated by build.mjs - DO NOT EDIT MANUALLY\nexport const U2NETP_MODEL_CHUNKS: string[] = ${JSON.stringify(chunks, null, 2)}\n`
  writeFileSync(chunksTsPath, content, 'utf-8')
  console.log(`📦 Packaged U²-NetP model into ${chunks.length} safe binary chunks (${stats.size} bytes)`)

  // Remove stale chunk files if present
  const staleChunks = [
    resolve(__dirname, 'src/ai/silueta_chunks.ts'),
    resolve(__dirname, 'src/ai/u2net_chunks.ts'),
  ]
  for (const stale of staleChunks) {
    if (existsSync(stale)) {
      rmSync(stale, { force: true })
      console.log(`🧹 Cleaned up stale ${stale.split(/[/\\]/).pop()}`)
    }
  }
}

// Package U²-NetP model before build
packageU2NetPModel()

const pluginOptions = {
  entryPoints: [resolve(__dirname, 'src/plugin/code.ts')],
  bundle: true,
  outfile: resolve(__dirname, 'dist/code.js'),
  format: /** @type {'cjs'} */ ('cjs'),
  target: 'es2017',
  logLevel: /** @type {'info'} */ ('info'),
  tsconfig: resolve(__dirname, 'tsconfig.plugin.json'),
}

console.log('🔨 Building DesignKit...\n')

if (isWatch) {
  console.log('👀 Watch mode — building continuously\n')

  const ctx = await esbuild.context(pluginOptions)
  await ctx.watch()
  console.log('✅ Plugin watcher started')

  await viteBuild({
    build: { watch: {} },
    logLevel: 'info',
  })
} else {
  // 1. Build plugin sandbox code
  await esbuild.build(pluginOptions)
  console.log('✅ Plugin code → dist/code.js')

  // 2. Build UI code with Vite
  await viteBuild()
  console.log('✅ UI → dist/index.html')

  // 3. Copy static assets to dist/assets
  const assetsSrc = resolve(__dirname, 'assets')
  const assetsDst = resolve(__dirname, 'dist/assets')
  if (existsSync(assetsSrc)) {
    cpSync(assetsSrc, assetsDst, { recursive: true })
    console.log('✅ Local Model Assets → dist/assets')
  }

  console.log('\n🎉 Build complete!')
  console.log('👉 In Figma: Plugins → Development → Import plugin from manifest')
  console.log('   Select: manifest.json in the project root\n')
}

